### ISSUE TITLE
Implement conditional executes

### ISSUE THREAD

**Issue by moritzheiber** [tooploox/oya#61]
I'd love to be able to tell a task to run or not run depending on either an environment variable or the result of a previous task (return value might suffice). An example would be conditional execution for operating systems or environments:

```
build:
  condition: is_macos
  command: ENV=macos ./build

build:
  condition: is_linux
  command: ENV=linux ./build
```

One could also implement this through "namespaces" depending on the condition:

```
Conditions:
  Linux: uname -o | grep -q Linux
  macOS: uname -o | grep -q Darwin

Linux:
  build: ENV=linux ./build

macOS:
  build: ENV=macos ./build
```
or
```
Conditions:
  Linux: uname -o | grep -q Linux
  macOS: uname -o | grep -q Darwin

build:
  Linux: ENV=linux ./build
  macOS: ENV=macos ./build
```

_Note: These are very trivial examples that don't necessarily make a lot of sense, but if Oya is to become the "executor of choice" for a team working across platforms it would be incredibly convenient to have a differentiator for these target platforms._

**Comment by bilus** [comment]
This is very interesting. While you can use `if` for conditional logic since it's just a bash interpreter, it would be nice to have something more declarative.

The way we want to allow extensions like this is using dot syntax. For example, this is how you can add docstrings to tasks even now (though it's not documented yet):

```yaml
build.Doc: Builds the system
build: |
  ./build
```

```
$ oya tasks
# in ./Oyafile
oya run anotherTask
oya run build        # Builds the system
```
