### ISSUE TITLE
Feature Request: Task descriptions 

### ISSUE THREAD

**Issue by reggi** [tooploox/oya#62]
I'd love to see descriptions in the `oya tasks` command of what a task is. 

```yml
Project: Example

descriptions: 
  meow: 'Say Meow'

meow: | 
    echo 'meow'

```

Then:

```
➜  oya-test oya tasks
oya run meow .......................... Say Meow    
```

It would be nice to have descriptions and arguments.

**Comment by reggi** [comment]
Here's an alternative idea, if a command is an object allow specific properties:

```yml
company.build-prod:
  description: Build production
  command: |
    docker-compose exec api yarn run tsc --pretty --project tsconfig.production.json

company.single-test: 
  description: Run a single test
  args: 
    file: 
      type: FILE
  command: |
    docker-compose exec api yarn test-pattern ${file}
```

**Comment by bilus** [comment]
@reggi Thanks for the suggestions!

As far as descriptions, it's already implemented (just not documented yet, sorry) using task meta-information syntax (`<task-name>.<meta-key>`):

```yaml
Project: aaa

build.Doc: Builds the system
build: |
  ./build
```

```
$ oya tasks
# in ./Oyafile
oya run anotherTask
oya run build        # Builds the system
```

In general, we have ideas for more of these extensions (including declarative argument checking and task dependencies).

As far as arguments, while there's no way to validate them (yet), there are ways you can access them beyond what bash supports (`$@`, `$1`, etc.):


```
Project: foo

build.Doc: Builds the system
build: |
  echo build ${Oya[Args.0]} ${Oya[Flags.all]} ${Oya[Flags.target]}
```

```
$ oya run build file.txt --all --target=ababa
build file.txt true ababa
```
